FROM eclipse-temurin:21-jdk as build
WORKDIR /app

COPY mvnw mvnw
COPY .mvn .mvn

RUN chmod +x mvnw
COPY pom.xml pom.xml
RUN ./mvnw dependency:go-offline

COPY src src

RUN ./mvnw clean package -DskipTests
FROM eclipse-temurin:21-jre

ARG PORT
ENV PORT=${PORT}

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

RUN useradd runtime
USER runtime

ENTRYPOINT [ "java", "-Dserver.port=${PORT}", "-jar", "app.jar"]
